run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
  gosec:
    excludes:
      - G204  # subprocess launched with variable — review each case

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
