# .goreleaser.yaml
version: 2
project_name: wardex

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

sboms:
  - id: cyclonedx
    artifacts: archive
    args: ["packages", "${artifact}", "-o", "cyclonedx-json", "--file", "${artifact}.sbom.json"]

signs:
  - id: cosign
    artifacts: all
    cmd: cosign
    args:
      - "sign-blob"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"

docker_signs:
  - id: cosign-keyless
    artifacts: all
    cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "${artifact}"
