// Copyright (c) 2025–2026 André Gustavo Leão de Melo Ataíde (had-nu). All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Wardex-Commercial

package report

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/had-nu/wardex/v2/pkg/cli"
	"github.com/had-nu/wardex/v2/pkg/model"
)

// ErrReportExpired indicates the gate report is older than the
// configured maximum allowed age (max_report_age).
var ErrReportExpired = errors.New("gate report is too old according to max_report_age")

// ReadReport reads and parses the JSON report generated by wardex.
// It returns the list of blocked vulnerabilities, the ReportHash, and any errors.
func ReadReport(path string, maxAgeHours int) ([]model.Vulnerability, string, error) {
	data, err := cli.SafeReadFile(path)
	if err != nil {
		return nil, "", fmt.Errorf("reading report file: %w", err)
	}

	hash := fmt.Sprintf("sha256:%x", sha256.Sum256(data))

	var rep model.GapReport
	if err := json.Unmarshal(data, &rep); err != nil {
		return nil, "", fmt.Errorf("parsing gate report: %w", err)
	}

	// Must have a gate report inside
	if rep.Gate == nil {
		return nil, "", errors.New("report does not contain release gate results")
	}

	// Validate Report Timestamp
	age := time.Since(rep.Summary.GeneratedAt)
	maxDur := time.Duration(maxAgeHours) * time.Hour
	if maxDur > 0 && age > maxDur {
		return nil, "", fmt.Errorf("%w: report is %v old, max allowed is %d hours", ErrReportExpired, age, maxAgeHours)
	}

	var blockedCVEs []model.Vulnerability
	for _, v := range rep.Gate.Decisions {
		if v.Decision == model.DecisionBlock {
			blockedCVEs = append(blockedCVEs, v.Vulnerability)
		}
	}

	return blockedCVEs, hash, nil
}
