package reporter

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/had-nu/wardex/pkg/model"
)

var (
	ErrReportExpired = errors.New("gate report is too old according to max_report_age")
)

// Read reads and parses the JSON report generated by wardex.
// It returns the list of blocked vulnerabilities, the ReportHash, and any errors.
func Read(path string, maxAgeHours int) ([]model.Vulnerability, string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, "", fmt.Errorf("reading report file: %w", err)
	}

	hash := fmt.Sprintf("sha256:%x", sha256.Sum256(data))

	var report model.GapReport
	if err := json.Unmarshal(data, &report); err != nil {
		return nil, "", fmt.Errorf("parsing gate report: %w", err)
	}

	// Must have a gate report inside
	if report.Gate == nil {
		return nil, "", errors.New("report does not contain release gate results")
	}

	// Validate Report Timestamp
	age := time.Since(report.Summary.GeneratedAt)
	maxDur := time.Duration(maxAgeHours) * time.Hour
	if maxDur > 0 && age > maxDur {
		return nil, "", fmt.Errorf("%w: report is %v old, max allowed is %d hours", ErrReportExpired, age, maxAgeHours)
	}

	var blockedCVEs []model.Vulnerability
	for _, v := range report.Gate.Decisions {
		if v.Decision == "block" {
			blockedCVEs = append(blockedCVEs, v.Vulnerability)
		}
	}

	return blockedCVEs, hash, nil
}
