// Copyright (c) 2025–2026 André Gustavo Leão de Melo Ataíde (had-nu). All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Wardex-Commercial

package accept

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/mail"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/had-nu/wardex/v2/config"
	"github.com/had-nu/wardex/v2/internal/cpl"
	"github.com/had-nu/wardex/v2/pkg/atomicwrite"
	"github.com/had-nu/wardex/v2/pkg/cli"
	"github.com/had-nu/wardex/v2/pkg/model"
	"gopkg.in/yaml.v3"
)

var (
	// ErrInvalidEmail indicates the accepted_by field is not a valid email.
	ErrInvalidEmail = errors.New("accepted_by must be a valid email address")
	// ErrJustificationShort indicates the justification does not meet the
	// minimum length requirement.
	ErrJustificationShort = errors.New("justification is too short")
	// ErrBannedPhrase indicates the justification contains a prohibited
	// phrase from the blocklist.
	ErrBannedPhrase = errors.New("justification contains banned phrases")
	// ErrExpiryTooLong indicates the requested expiration exceeds the
	// configured maximum TTL.
	ErrExpiryTooLong = errors.New("expiration date exceeds maximum allowed limit")
	// ErrReportExpired indicates the gate report is older than the
	// configured max_report_age and can no longer be used.
	ErrReportExpired = errors.New("gate report is too old according to max_report_age")
)

// ReadReport reads and parses the JSON report generated by wardex.
// It returns the list of blocked vulnerabilities, the ReportHash, and any errors.
func ReadReport(path string, maxAgeHours int) ([]model.Vulnerability, string, error) {
	safePathStr, err := cli.SafePath(path)
	if err != nil {
		return nil, "", err
	}
	data, err := os.ReadFile(safePathStr) // #nosec G304
	if err != nil {
		return nil, "", fmt.Errorf("reading report file: %w", err)
	}

	hash := fmt.Sprintf("sha256:%x", sha256.Sum256(data))

	var report model.GapReport
	if err := json.Unmarshal(data, &report); err != nil {
		return nil, "", fmt.Errorf("parsing gate report: %w", err)
	}

	// Must have a gate report inside
	if report.Gate == nil {
		return nil, "", errors.New("report does not contain release gate results")
	}

	// Validate Report Timestamp
	age := time.Since(report.Summary.GeneratedAt)
	maxDur := time.Duration(maxAgeHours) * time.Hour
	if maxDur > 0 && age > maxDur {
		return nil, "", fmt.Errorf("%w: report is %v old, max allowed is %d hours", ErrReportExpired, age, maxAgeHours)
	}

	var blockedCVEs []model.Vulnerability
	for _, v := range report.Gate.Decisions {
		if v.Decision == model.DecisionBlock {
			blockedCVEs = append(blockedCVEs, v.Vulnerability)
		}
	}

	return blockedCVEs, hash, nil
}

// Result represents the verification result of an Acceptance.
type Result struct {
	Acceptance     model.Acceptance
	Valid          bool
	Expired        bool
	Tampered       bool
	Stale          bool // config mudou desde a aceitação
	ReportMismatch bool // GateReport actual diverge do original
	ExpiresIn      time.Duration
	Errors         []string
}

// ErrStoreInconsistent is returned when the acceptance store has fewer YAML
// entries than audit log events, indicating possible tampering or data loss.
var ErrStoreInconsistent = errors.New("store inconsistency: yaml entries < audit log events")

// Load reads wardex-acceptances.yaml and sequentially executes verify logic.
// Rejected acceptances (expired, tampered, revoked) are logged to logw when non-nil.
func Load(path string, key []byte, auditPath string, currentReportHash string, currentConfigHash string, logw io.Writer) ([]model.Acceptance, error) {
	safePathStr, err := cli.SafePath(path)
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(safePathStr) // #nosec G304
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil // First time
		}
		return nil, err
	}

	var store model.AcceptanceStore
	if err := yaml.Unmarshal(data, &store); err != nil {
		return nil, fmt.Errorf("failed to parse acceptances: %w", err)
	}

	countCreated, err := AuditCountCreated(auditPath)
	if err != nil {
		return nil, fmt.Errorf("failed to count audit log events: %w", err)
	}

	if len(store.Acceptances) < countCreated {
		return nil, ErrStoreInconsistent
	}

	results, allValid := VerifyAll(store.Acceptances, key, currentReportHash, currentConfigHash)
	if !allValid {
		for _, res := range results {
			if res.Tampered {
				return nil, fmt.Errorf("tampered acceptance detected: entry %s failed signature validation", res.Acceptance.ID)
			}
		}
	}

	// Return only non-expired and valid, logging rejections
	var validAcceptances []model.Acceptance
	for _, res := range results {
		if res.Valid {
			validAcceptances = append(validAcceptances, res.Acceptance)
		} else if logw != nil {
			reason := "unknown"
			switch {
			case res.Expired:
				reason = "expired"
			case res.Tampered:
				reason = "tampered"
			case res.Stale:
				reason = "config changed since acceptance"
			case res.ReportMismatch:
				reason = "report hash mismatch"
			}
			fmt.Fprintf(logw, "[REJECT] Acceptance %s for %s — %s\n", res.Acceptance.ID, res.Acceptance.CVE, reason)
		}
	}

	return validAcceptances, nil
}

// Append atomically writes a new Acceptance to the store
func Append(path string, a model.Acceptance) error {
	safePathStr, err := cli.SafePath(path)
	if err != nil {
		return err
	}
	dir := filepath.Dir(safePathStr)
	if err := os.MkdirAll(dir, 0750); err != nil {
		return err
	}

	// Read existing
	data, err := os.ReadFile(safePathStr) // #nosec G304
	var store model.AcceptanceStore
	if err == nil {
		if err := yaml.Unmarshal(data, &store); err != nil {
			return err
		}
	}
	store.Acceptances = append(store.Acceptances, a)

	out, err := yaml.Marshal(store)
	if err != nil {
		return err
	}

	return atomicwrite.Write(safePathStr, out)
}

// UpdateStatus actualiza status e RevocationRecord. Regenera assinatura.
func UpdateStatus(path string, id string, status string, revocation *model.RevocationRecord, key []byte) error {
	safePathStr, err := cli.SafePath(path)
	if err != nil {
		return err
	}
	data, err := os.ReadFile(safePathStr) // #nosec G304
	if err != nil {
		return err
	}

	var store model.AcceptanceStore
	if err := yaml.Unmarshal(data, &store); err != nil {
		return err
	}

	found := false
	for i, a := range store.Acceptances {
		if a.ID == id {
			if status == "revoked" {
				store.Acceptances[i].Revoked = true
				if revocation != nil {
					store.Acceptances[i].RevokedBy = revocation.RevokedBy
					store.Acceptances[i].RevokedAt = revocation.RevokedAt
					store.Acceptances[i].RevokeReason = revocation.Reason
					store.Acceptances[i].Revocation = revocation
				}
			}

			// Regenerate signature
			sig, err := Sign(store.Acceptances[i], key)
			if err != nil {
				return err
			}
			store.Acceptances[i].Signature = sig

			found = true
			break
		}
	}

	if !found {
		return fmt.Errorf("acceptance ID %s not found", id)
	}

	out, err := yaml.Marshal(store)
	if err != nil {
		return err
	}

	return atomicwrite.Write(safePathStr, out)
}

// ValidateBusinessRules enforces acceptance constraints against the config limits.
func ValidateBusinessRules(a model.Acceptance, cfg config.AcceptanceConfig) error {
	// 1. Email constraint
	if _, err := mail.ParseAddress(a.AcceptedBy); err != nil {
		return ErrInvalidEmail
	}

	// 2. Justification minimum characters
	minChars := cfg.Limits.MinJustificationChars
	if minChars == 0 {
		minChars = 80 // Sensible default according to specs
	}
	if len(strings.TrimSpace(a.Justification)) < minChars {
		return fmt.Errorf("%w: minimum %d characters required", ErrJustificationShort, minChars)
	}

	// 3. Banned phrases check
	lowerJustification := strings.ToLower(a.Justification)
	for _, phrase := range cfg.BannedJustificationPhrases {
		if phrase != "" && strings.Contains(lowerJustification, strings.ToLower(phrase)) {
			return fmt.Errorf("%w: '%s'", ErrBannedPhrase, phrase)
		}
	}

	// 4. Maximum Expiry Check
	maxDays := cfg.Limits.MaxAcceptanceDays
	if maxDays == 0 {
		maxDays = 30 // Sensible default
	}

	maxDuration := time.Duration(maxDays) * 24 * time.Hour
	// To prevent slight drifts causing errors, we allow a tiny buffer
	if time.Until(a.ExpiresAt) > maxDuration+(1*time.Hour) {
		return fmt.Errorf("%w: maximum allowed is %d days", ErrExpiryTooLong, maxDays)
	}

	return nil
}

// VerifyAll verifies the signature, expiry, and hashes for multiple acceptances.
func VerifyAll(acceptances []model.Acceptance, key []byte, currentReportHash string, currentConfigHash string) ([]Result, bool) {
	var results []Result
	allValid := true

	for _, a := range acceptances {
		res := Result{Acceptance: a}

		if err := Verify(a, key); err != nil {
			res.Tampered = true
			res.Errors = append(res.Errors, err.Error())
			allValid = false
		}

		if !a.ExpiresAt.IsZero() && time.Now().After(a.ExpiresAt) {
			res.Expired = true
			res.Errors = append(res.Errors, "acceptance has expired")
			allValid = false
		} else {
			res.ExpiresIn = time.Until(a.ExpiresAt)
		}

		// Validation succeeds if its non tampered and non expired
		if !res.Tampered && !res.Expired {
			res.Valid = true
		}
		results = append(results, res)
	}

	return results, allValid
}

// ConfigHash calculates the canonical SHA-256 hash of the configuration file.
// Uses the CPL canonicalisation (sorted keys, no comments, normalised whitespace).
func ConfigHash(configPath string) (string, error) {
	safePathStr, err := cli.SafePath(configPath)
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(safePathStr) // #nosec G304
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil // Sem config file, hash vazio
		}
		return "", fmt.Errorf("reading config file for audit: %w", err)
	}

	return cpl.ComputeConfigHash(data, cpl.AlgoSHA256)
}

// ConfigCheck compares the current config hash with the last recorded one in the audit log.
func ConfigCheck(configPath string, auditPath string, notifyFunc func(event string, oldHash, newHash string)) (bool, error) {
	currentHash, err := ConfigHash(configPath)
	if err != nil {
		return false, err
	}

	// Simple simulation of finding the 'prevHash'.
	changed := false
	prevHash := ""

	event := "config.loaded"
	if changed {
		event = "config.changed"
		if notifyFunc != nil {
			notifyFunc(event, prevHash, currentHash)
		}
	}

	err = AuditLog(auditPath, model.AuditEntry{
		Timestamp:  time.Now(),
		Event:      event,
		ConfigHash: currentHash,
		PrevHash:   prevHash,
	})

	return changed, err
}
