// Copyright (c) 2025–2026 André Gustavo Leão de Melo Ataíde (had-nu). All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Wardex-Commercial

// Package accept is the backward-compatible re-export facade for the Wardex
// acceptance workflow, decomposed into sub-packages in v2.5:
//
//	pkg/accept/store    — persistence (Load, Append, UpdateStatus)
//	pkg/accept/verify   — signature/expiry verification (Sign, Verify, VerifyAll)
//	pkg/accept/audit    — chained audit log (ChainedAuditLog, AuditLog, VerifyChain)
//	pkg/accept/forward  — forwarding backends (webhook, syslog, ENISA stub)
//	pkg/accept/rules    — business rules (ValidateBusinessRules)
//
// Deprecated: prefer importing the specific sub-package. This facade is kept
// for backward compatibility in v2.5 and will be removed in v3.0.
package accept

import (
	"io"
	"time"

	"github.com/had-nu/wardex/v2/config"
	"github.com/had-nu/wardex/v2/internal/cpl"
	"github.com/had-nu/wardex/v2/pkg/accept/audit"
	"github.com/had-nu/wardex/v2/pkg/accept/forward"
	"github.com/had-nu/wardex/v2/pkg/accept/rules"
	"github.com/had-nu/wardex/v2/pkg/accept/store"
	"github.com/had-nu/wardex/v2/pkg/accept/verify"
	"github.com/had-nu/wardex/v2/pkg/model"
	"github.com/had-nu/wardex/v2/pkg/report"
)

// ErrInvalidEmail is re-exported from pkg/accept/rules.
var ErrInvalidEmail = rules.ErrInvalidEmail

// ErrJustificationShort is re-exported from pkg/accept/rules.
var ErrJustificationShort = rules.ErrJustificationShort

// ErrBannedPhrase is re-exported from pkg/accept/rules.
var ErrBannedPhrase = rules.ErrBannedPhrase

// ErrExpiryTooLong is re-exported from pkg/accept/rules.
var ErrExpiryTooLong = rules.ErrExpiryTooLong

// ErrReportExpired is re-exported from pkg/report.
var ErrReportExpired = report.ErrReportExpired

// ErrStoreInconsistent is re-exported from pkg/accept/store.
var ErrStoreInconsistent = store.ErrStoreInconsistent

// ErrTampered is re-exported from pkg/accept/verify.
var ErrTampered = verify.ErrTampered

// ErrLiteralSecret is re-exported from pkg/accept/verify.
var ErrLiteralSecret = verify.ErrLiteralSecret

// ReadReport reads and parses the JSON gate report generated by wardex.
//
// Deprecated: moved to pkg/report. Re-export for backward compatibility.
func ReadReport(path string, maxAgeHours int) ([]model.Vulnerability, string, error) {
	return report.ReadReport(path, maxAgeHours)
}

// ConfigHash calculates the canonical SHA-256 hash of the configuration file.
//
// Deprecated: moved to internal/cpl. Re-export for backward compatibility.
func ConfigHash(configPath string) (string, error) {
	return cpl.ConfigHash(configPath)
}

// ConfigCheck compares the current config hash with the last recorded one in the audit log.
func ConfigCheck(configPath string, auditPath string, notifyFunc func(event string, oldHash, newHash string)) (bool, error) {
	currentHash, err := cpl.ConfigHash(configPath)
	if err != nil {
		return false, err
	}

	// Simple simulation of finding the 'prevHash'.
	changed := false
	prevHash := ""

	event := "config.loaded"
	if changed {
		event = "config.changed"
		if notifyFunc != nil {
			notifyFunc(event, prevHash, currentHash)
		}
	}

	err = audit.AuditLog(auditPath, model.AuditEntry{
		Timestamp:  time.Now(),
		Event:      event,
		ConfigHash: currentHash,
		PrevHash:   prevHash,
	})

	return changed, err
}

// Result is re-exported from pkg/accept/verify.
type Result = verify.Result

// Load is re-exported from pkg/accept/store.
func Load(path string, key []byte, auditPath string, currentReportHash string, currentConfigHash string, logw io.Writer) ([]model.Acceptance, error) {
	return store.Load(path, key, auditPath, currentReportHash, currentConfigHash, logw)
}

// Append is re-exported from pkg/accept/store.
func Append(path string, a model.Acceptance) error {
	return store.Append(path, a)
}

// UpdateStatus is re-exported from pkg/accept/store.
func UpdateStatus(path string, id string, status string, revocation *model.RevocationRecord, key []byte) error {
	return store.UpdateStatus(path, id, status, revocation, key)
}

// Sign is re-exported from pkg/accept/verify.
func Sign(a model.Acceptance, key []byte) (string, error) {
	return verify.Sign(a, key)
}

// Verify is re-exported from pkg/accept/verify.
func Verify(a model.Acceptance, key []byte) error {
	return verify.Verify(a, key)
}

// VerifyAll is re-exported from pkg/accept/verify.
func VerifyAll(acceptances []model.Acceptance, key []byte, currentReportHash string, currentConfigHash string) ([]Result, bool) {
	return verify.VerifyAll(acceptances, key, currentReportHash, currentConfigHash)
}

// ResolveSecret is re-exported from pkg/accept/verify.
func ResolveSecret(cfg config.Config) ([]byte, error) {
	return verify.ResolveSecret(cfg)
}

// ValidateBusinessRules is re-exported from pkg/accept/rules.
func ValidateBusinessRules(a model.Acceptance, cfg config.AcceptanceConfig) error {
	return rules.ValidateBusinessRules(a, cfg)
}

// AuditLog is re-exported from pkg/accept/audit.
func AuditLog(path string, entry model.AuditEntry) error {
	return audit.AuditLog(path, entry)
}

// AuditCountCreated is re-exported from pkg/accept/audit.
func AuditCountCreated(path string) (int, error) {
	return audit.AuditCountCreated(path)
}

// ChainedAuditLog is re-exported from pkg/accept/audit.
func ChainedAuditLog(path string, entry model.AuditEntry) error {
	return audit.ChainedAuditLog(path, entry)
}

// LastEntryHash is re-exported from pkg/accept/audit.
func LastEntryHash(path string) (string, error) {
	return audit.LastEntryHash(path)
}

// VerifyChain is re-exported from pkg/accept/audit.
func VerifyChain(path string) ([]ChainGap, error) {
	return audit.VerifyChain(path)
}

// ChainGap is re-exported from pkg/accept/audit.
type ChainGap = audit.ChainGap

// Forwarder is re-exported from pkg/accept/forward.
type Forwarder = forward.Forwarder

// ForwardMultiplexer is re-exported from pkg/accept/forward.
type ForwardMultiplexer = forward.ForwardMultiplexer

// NewForwardMultiplexer is re-exported from pkg/accept/forward.
func NewForwardMultiplexer(backends []Forwarder, onFail string) *ForwardMultiplexer {
	return forward.NewForwardMultiplexer(backends, onFail)
}

// Notifier is re-exported from pkg/accept/forward.
type Notifier = forward.Notifier

// NotifyMultiplexer is re-exported from pkg/accept/forward.
type NotifyMultiplexer = forward.NotifyMultiplexer

// NewNotifyMultiplexer is re-exported from pkg/accept/forward.
func NewNotifyMultiplexer(channels []Notifier) *NotifyMultiplexer {
	return forward.NewNotifyMultiplexer(channels)
}

// WebhookNotifier is re-exported from pkg/accept/forward.
type WebhookNotifier = forward.WebhookNotifier

// NewWebhookNotifier is re-exported from pkg/accept/forward.
func NewWebhookNotifier(url, tmplDir string, events []string) *WebhookNotifier {
	return forward.NewWebhookNotifier(url, tmplDir, events)
}

// NotificationEvent is re-exported from pkg/accept/forward.
type NotificationEvent = forward.NotificationEvent

// ENISABackend is re-exported from pkg/accept/forward.
type ENISABackend = forward.ENISABackend

// NewENISABackend is re-exported from pkg/accept/forward.
func NewENISABackend(queuePath string) *ENISABackend {
	return forward.NewENISABackend(queuePath)
}

// SyslogBackend is re-exported from pkg/accept/forward.
type SyslogBackend = forward.SyslogBackend

// NewSyslogBackend is re-exported from pkg/accept/forward.
func NewSyslogBackend(address, protocol, facility string) (*SyslogBackend, error) {
	return forward.NewSyslogBackend(address, protocol, facility)
}
